default:
  image: node:alpine
  before_script:
    - yarn
    - cd api
    - yarn
    - cd ..
    - cd web
    - yarn
    - cd ..

services:
  - mongo

eslint:
  script:
    - yarn lint

cypress:
  image: cypress/base
  script:
    - yarn ci:p2p:headless
