default:
  image: node:alpine
  before_script:
    - yarn
    - cd api
    - yarn
    - cd ..
    - cd web
    - yarn
    - cd ..

lint:
  script:
    - yarn lint

test-api:
  script:
    - cd api
    - yarn test

test-populate-posts:
  script:
    - cd populate-posts
    - yarn test

test-cypress:
  image: cypress/base
  script:
    - yarn ci:p2p:headless
