image: node:latest

services:
  - mongo

stages:
  # - lint
  - cypress

eslint:
  stage: lint
  script:
    - yarn
    - yarn lint
    - yarn test:p2p:headless

cypress:
  stage: cypress
  script:
    - yarn
    - cd api
    - yarn
    - cd ..
    - cd web
    - yarn
    - cd ..
    - yarn ci:p2p:headless
