image: node:latest

stages:
  - deps
  - lint
  - cypress

deps:
  stage: deps
  script:
    - yarn
    - cd api
    - yarn
    - cd ..
    - cd web
    - yarn
    - cd ..

eslint:
  stage: lint
  script:
    - yarn lint
    - yarn test:p2p:headless

cypress:
  stage: cypress
  script:
    - yarn test:p2p:headless
