version: "3"

services:
  api:
    image: reign/api
    environment:
      - MONGO=mongodb://mongo/reign
    ports:
      - 5000:5000
    links:
      - mongo

  web:
    image: reign/web
    environment:
      - MONGO=mongodb://mongo/reign
    ports:
      - 3000:3000

  populate-posts:
    image: reign/populate-posts
    environment:
      - MONGO=mongodb://mongo/reign
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
  
volumes:
  data:
  letsencrypt:
  certbot:
